import { Outfit as OutfitFont, Ovo as OvoFont } from 'next/font/google'
import './globals.css'
import type { Metadata } from 'next'

const outfit = OutfitFont({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})
const ovo = OvoFont({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Portfilio - Zohanubis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className='scroll-smooth dark'>
      <body
      // Leading-8 is the line height
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
  )
}
